repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.11.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: tests/fixtures/xfail/missing-newline-at-end-of-file.rst
      - id: trailing-whitespace
        exclude: tests/fixtures/xfail/trailing-whitespaces.rst

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
