[build-system]
build-backend = "hatchling.build"
requires = [
  "hatch-vcs",
  "hatchling",
]

[project]
name = "sphinx-lint"
description = "Check for stylistic and formal issues in .rst and .py files included in the documentation."
readme = "README.md"
license = {text = "PSF License"}
authors = [
    {name = "Georg Brandl", email = "georg@python.org"},
    {name = "Julien Palard", email = "julien@palard.fr"},
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Documentation :: Sphinx",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Python Software Foundation License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
]
requires-python = ">= 3.8"
dependencies = [
    "regex",
    "polib",
]
dynamic = ["version"]


[project.optional-dependencies]
tests = [
  "pytest",
  "pytest-cov",
]
[project.urls]
Repository = "https://github.com/sphinx-contrib/sphinx-lint"
Changelog = "https://github.com/sphinx-contrib/sphinx-lint/releases"

[project.scripts]
sphinx-lint = "sphinxlint.cli:main"

[tool.hatch]
version.source = "vcs"

[tool.hatch.version.raw-options]
local_scheme = "no-local-version"

[tool.black]

[tool.ruff]
select = [
  "E", # pycodestyle errors
  "F", # pyflakes errors
  "I", # isort
  "ISC", # flake8-implicit-str-concat
  "PGH", # pygrep-hooks
  "RUF100", # unused noqa (yesqa)
  "UP", # pyupgrade
  "W", # pycodestyle warnings
  "YTT", # flake8-2020
]
extend-ignore = [
  "E203", # Whitespace before ':'
  "E221", # Multiple spaces before operator
  "E226", # Missing whitespace around arithmetic operator
  "E241", # Multiple spaces after ','
]

[tool.pylint.variables]
callbacks = ["check_"]
