name: Tests with Tox

on: [push, pull_request, workflow_dispatch]

env:
  FORCE_COLOR: 1

concurrency:
  group: check-tests-tox-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    name: test with py${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        exclude:
          # TODO Add Windows when regex wheel available for 3.13
          - {os: windows-latest, py: "3.13"}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
          allow-prereleases: true
          cache: pip
      - name: Download more tests from friend projects
        if: matrix.py == '3.13' && runner.os == 'Linux'
        run: sh download-more-tests.sh

      - name: Install tox
        run: python -m pip install tox-gh>=1.2
      - name: Setup test suite
        run: tox -vv --notest
      - name: Run test suite
        run: tox --skip-pkg-install

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          flags: ${{ matrix.os }}
          name: ${{ matrix.os }} Python ${{ matrix.py }}
